### ISSUE TITLE
json link broken

### ISSUE THREAD

**Issue by LokiMetaSmith** [h2zero/n-able-Arduino#2]
Add https://h2zero.github.io/n-able-Arduino/package_n-able_boards_index.json as an "Additional Board Manager URL"

This returns a 404 error

**Comment by h2zero** [comment]
Hi @LokiMetaSmith, thank you for trying it out. The link is broken due to not yet (very soon) having created a release so the information required for the json file is not yet available. 

Once a release is created I will make the json file and upload it. Sorry for your troubles, this should have been noted in the readme.

**Comment by h2zero** [comment]
@LokiMetaSmith This should now be resolved, first release is now available 🥳

**Comment by LokiMetaSmith** [comment]
Looks like it's working now, thanks!
